#ifndef scancodeToKeyIdentifier_h
#define scancodeToKeyIdentifier_h

namespace RmlSDL {

inline Rml::Input::KeyIdentifier ConvertKey(SDL_Scancode sc) {
    using namespace Rml::Input;
    switch (sc) {
        // --- Alnum ---
        case SDL_SCANCODE_A: return KI_A;
        case SDL_SCANCODE_B: return KI_B;
        case SDL_SCANCODE_C: return KI_C;
        case SDL_SCANCODE_D: return KI_D;
        case SDL_SCANCODE_E: return KI_E;
        case SDL_SCANCODE_F: return KI_F;
        case SDL_SCANCODE_G: return KI_G;
        case SDL_SCANCODE_H: return KI_H;
        case SDL_SCANCODE_I: return KI_I;
        case SDL_SCANCODE_J: return KI_J;
        case SDL_SCANCODE_K: return KI_K;
        case SDL_SCANCODE_L: return KI_L;
        case SDL_SCANCODE_M: return KI_M;
        case SDL_SCANCODE_N: return KI_N;
        case SDL_SCANCODE_O: return KI_O;
        case SDL_SCANCODE_P: return KI_P;
        case SDL_SCANCODE_Q: return KI_Q;
        case SDL_SCANCODE_R: return KI_R;
        case SDL_SCANCODE_S: return KI_S;
        case SDL_SCANCODE_T: return KI_T;
        case SDL_SCANCODE_U: return KI_U;
        case SDL_SCANCODE_V: return KI_V;
        case SDL_SCANCODE_W: return KI_W;
        case SDL_SCANCODE_X: return KI_X;
        case SDL_SCANCODE_Y: return KI_Y;
        case SDL_SCANCODE_Z: return KI_Z;
        case SDL_SCANCODE_0: return KI_0;
        case SDL_SCANCODE_1: return KI_1;
        case SDL_SCANCODE_2: return KI_2;
        case SDL_SCANCODE_3: return KI_3;
        case SDL_SCANCODE_4: return KI_4;
        case SDL_SCANCODE_5: return KI_5;
        case SDL_SCANCODE_6: return KI_6;
        case SDL_SCANCODE_7: return KI_7;
        case SDL_SCANCODE_8: return KI_8;
        case SDL_SCANCODE_9: return KI_9;
        // --- Control ---
        case SDL_SCANCODE_SPACE: return KI_SPACE;
        case SDL_SCANCODE_RETURN: return KI_RETURN;
        case SDL_SCANCODE_ESCAPE: return KI_ESCAPE;
        case SDL_SCANCODE_BACKSPACE: return KI_BACK;
        case SDL_SCANCODE_TAB: return KI_TAB;
        case SDL_SCANCODE_CLEAR: return KI_CLEAR;
        case SDL_SCANCODE_CAPSLOCK: return KI_CAPITAL;
        // --- Navigation ---
        case SDL_SCANCODE_PAGEUP: return KI_PRIOR;
        case SDL_SCANCODE_PAGEDOWN: return KI_NEXT;
        case SDL_SCANCODE_END: return KI_END;
        case SDL_SCANCODE_HOME: return KI_HOME;
        case SDL_SCANCODE_LEFT: return KI_LEFT;
        case SDL_SCANCODE_UP: return KI_UP;
        case SDL_SCANCODE_RIGHT: return KI_RIGHT;
        case SDL_SCANCODE_DOWN: return KI_DOWN;
        case SDL_SCANCODE_SELECT: return KI_SELECT;
        case SDL_SCANCODE_PRINTSCREEN: return KI_SNAPSHOT;
        case SDL_SCANCODE_EXECUTE: return KI_EXECUTE;
        case SDL_SCANCODE_INSERT: return KI_INSERT;
        case SDL_SCANCODE_DELETE: return KI_DELETE;
        case SDL_SCANCODE_HELP: return KI_HELP;
        // --- Function ---
        case SDL_SCANCODE_F1: return KI_F1;
        case SDL_SCANCODE_F2: return KI_F2;
        case SDL_SCANCODE_F3: return KI_F3;
        case SDL_SCANCODE_F4: return KI_F4;
        case SDL_SCANCODE_F5: return KI_F5;
        case SDL_SCANCODE_F6: return KI_F6;
        case SDL_SCANCODE_F7: return KI_F7;
        case SDL_SCANCODE_F8: return KI_F8;
        case SDL_SCANCODE_F9: return KI_F9;
        case SDL_SCANCODE_F10: return KI_F10;
        case SDL_SCANCODE_F11: return KI_F11;
        case SDL_SCANCODE_F12: return KI_F12;
        case SDL_SCANCODE_F13: return KI_F13;
        case SDL_SCANCODE_F14: return KI_F14;
        case SDL_SCANCODE_F15: return KI_F15;
        case SDL_SCANCODE_F16: return KI_F16;
        case SDL_SCANCODE_F17: return KI_F17;
        case SDL_SCANCODE_F18: return KI_F18;
        case SDL_SCANCODE_F19: return KI_F19;
        case SDL_SCANCODE_F20: return KI_F20;
        case SDL_SCANCODE_F21: return KI_F21;
        case SDL_SCANCODE_F22: return KI_F22;
        case SDL_SCANCODE_F23: return KI_F23;
        case SDL_SCANCODE_F24: return KI_F24;
        // --- Keypad ---
        case SDL_SCANCODE_KP_0: return KI_NUMPAD0;
        case SDL_SCANCODE_KP_1: return KI_NUMPAD1;
        case SDL_SCANCODE_KP_2: return KI_NUMPAD2;
        case SDL_SCANCODE_KP_3: return KI_NUMPAD3;
        case SDL_SCANCODE_KP_4: return KI_NUMPAD4;
        case SDL_SCANCODE_KP_5: return KI_NUMPAD5;
        case SDL_SCANCODE_KP_6: return KI_NUMPAD6;
        case SDL_SCANCODE_KP_7: return KI_NUMPAD7;
        case SDL_SCANCODE_KP_8: return KI_NUMPAD8;
        case SDL_SCANCODE_KP_9: return KI_NUMPAD9;
        case SDL_SCANCODE_KP_ENTER: return KI_NUMPADENTER;
        case SDL_SCANCODE_KP_MULTIPLY: return KI_MULTIPLY;
        case SDL_SCANCODE_KP_PLUS: return KI_ADD;
        case SDL_SCANCODE_KP_MINUS: return KI_SUBTRACT;
        case SDL_SCANCODE_KP_PERIOD: return KI_DECIMAL;
        case SDL_SCANCODE_KP_DIVIDE: return KI_DIVIDE;
        case SDL_SCANCODE_KP_EQUALS: return KI_OEM_NEC_EQUAL;
        case SDL_SCANCODE_KP_EQUALSAS400: return KI_OEM_NEC_EQUAL;
        // --- OEM ---
        case SDL_SCANCODE_SEMICOLON: return KI_OEM_1;
        case SDL_SCANCODE_EQUALS: return KI_OEM_PLUS;
        case SDL_SCANCODE_COMMA: return KI_OEM_COMMA;
        case SDL_SCANCODE_MINUS: return KI_OEM_MINUS;
        case SDL_SCANCODE_PERIOD: return KI_OEM_PERIOD;
        case SDL_SCANCODE_SLASH: return KI_OEM_2;
        case SDL_SCANCODE_GRAVE: return KI_OEM_3;
        case SDL_SCANCODE_LEFTBRACKET: return KI_OEM_4;
        case SDL_SCANCODE_BACKSLASH: return KI_OEM_5;
        case SDL_SCANCODE_RIGHTBRACKET: return KI_OEM_6;
        case SDL_SCANCODE_APOSTROPHE: return KI_OEM_7;
        case SDL_SCANCODE_NONUSBACKSLASH: return KI_OEM_102;
        // --- Modifiers ---
        case SDL_SCANCODE_LSHIFT: return KI_LSHIFT;
        case SDL_SCANCODE_RSHIFT: return KI_RSHIFT;
        case SDL_SCANCODE_LCTRL: return KI_LCONTROL;
        case SDL_SCANCODE_RCTRL: return KI_RCONTROL;
        case SDL_SCANCODE_LALT: return KI_LMENU;
        case SDL_SCANCODE_RALT: return KI_RMENU;
        case SDL_SCANCODE_LGUI: return KI_LWIN;
        case SDL_SCANCODE_RGUI: return KI_RWIN;
        // --- Locks ---
        case SDL_SCANCODE_NUMLOCKCLEAR: return KI_NUMLOCK;
        case SDL_SCANCODE_SCROLLLOCK: return KI_SCROLL;
        case SDL_SCANCODE_PAUSE: return KI_PAUSE;
        // --- Browser ---
        case SDL_SCANCODE_AC_BACK: return KI_BROWSER_BACK;
        case SDL_SCANCODE_AC_FORWARD: return KI_BROWSER_FORWARD;
        case SDL_SCANCODE_AC_REFRESH: return KI_BROWSER_REFRESH;
        case SDL_SCANCODE_AC_STOP: return KI_BROWSER_STOP;
        case SDL_SCANCODE_AC_SEARCH: return KI_BROWSER_SEARCH;
        case SDL_SCANCODE_AC_BOOKMARKS: return KI_BROWSER_FAVORITES;
        case SDL_SCANCODE_AC_HOME: return KI_BROWSER_HOME;
        // --- Media ---
        case SDL_SCANCODE_VOLUMEUP: return KI_VOLUME_UP;
        case SDL_SCANCODE_VOLUMEDOWN: return KI_VOLUME_DOWN;
        case SDL_SCANCODE_MUTE: return KI_VOLUME_MUTE;
        // --- System ---
        case SDL_SCANCODE_APPLICATION: return KI_APPS;
        case SDL_SCANCODE_POWER: return KI_POWER;
        case SDL_SCANCODE_SLEEP: return KI_SLEEP;
        case SDL_SCANCODE_WAKE: return KI_WAKE;
        default: return KI_UNKNOWN;
    }
}

} // namespace RmlSDL

#endif /* scancodeToKeyIdentifier_h */