#include "scancodeToKeyIdentifier.h"

#include <SDL3/SDL_version.h>
#include <SDL3/SDL_keyboard.h>
#include <SDL3/SDL_keycode.h>

Rml::Input::KeyIdentifier RmlSDL::ScancodeToKeyIdentifier(SDL_Scancode sc) {
    using namespace Rml::Input;
    switch (sc) {
        // --- Alnum ---
        case SDL_SCANCODE_A: return KI_A;
        case SDL_SCANCODE_B: return KI_B;
        case SDL_SCANCODE_C: return KI_C;
        case SDL_SCANCODE_D: return KI_D;
        case SDL_SCANCODE_E: return KI_E;
        case SDL_SCANCODE_F: return KI_F;
        case SDL_SCANCODE_G: return KI_G;
        case SDL_SCANCODE_H: return KI_H;
        case SDL_SCANCODE_I: return KI_I;
        case SDL_SCANCODE_J: return KI_J;
        case SDL_SCANCODE_K: return KI_K;
        case SDL_SCANCODE_L: return KI_L;
        case SDL_SCANCODE_M: return KI_M;
        case SDL_SCANCODE_N: return KI_N;
        case SDL_SCANCODE_O: return KI_O;
        case SDL_SCANCODE_P: return KI_P;
        case SDL_SCANCODE_Q: return KI_Q;
        case SDL_SCANCODE_R: return KI_R;
        case SDL_SCANCODE_S: return KI_S;
        case SDL_SCANCODE_T: return KI_T;
        case SDL_SCANCODE_U: return KI_U;
        case SDL_SCANCODE_V: return KI_V;
        case SDL_SCANCODE_W: return KI_W;
        case SDL_SCANCODE_X: return KI_X;
        case SDL_SCANCODE_Y: return KI_Y;
        case SDL_SCANCODE_Z: return KI_Z;
        case SDL_SCANCODE_0: return KI_0;
        case SDL_SCANCODE_1: return KI_1;
        case SDL_SCANCODE_2: return KI_2;
        case SDL_SCANCODE_3: return KI_3;
        case SDL_SCANCODE_4: return KI_4;
        case SDL_SCANCODE_5: return KI_5;
        case SDL_SCANCODE_6: return KI_6;
        case SDL_SCANCODE_7: return KI_7;
        case SDL_SCANCODE_8: return KI_8;
        case SDL_SCANCODE_9: return KI_9;
        // --- Control ---
        case SDL_SCANCODE_SPACE: return KI_SPACE;
        case SDL_SCANCODE_RETURN: return KI_RETURN;
        case SDL_SCANCODE_ESCAPE: return KI_ESCAPE;
        case SDL_SCANCODE_BACKSPACE: return KI_BACK;
        case SDL_SCANCODE_TAB: return KI_TAB;
        case SDL_SCANCODE_CLEAR: return KI_CLEAR;
        case SDL_SCANCODE_CAPSLOCK: return KI_CAPITAL;
        // --- Navigation ---
        case SDL_SCANCODE_PAGEUP: return KI_PRIOR;
        case SDL_SCANCODE_PAGEDOWN: return KI_NEXT;
        case SDL_SCANCODE_END: return KI_END;
        case SDL_SCANCODE_HOME: return KI_HOME;
        case SDL_SCANCODE_LEFT: return KI_LEFT;
        case SDL_SCANCODE_UP: return KI_UP;
        case SDL_SCANCODE_RIGHT: return KI_RIGHT;
        case SDL_SCANCODE_DOWN: return KI_DOWN;
        case SDL_SCANCODE_SELECT: return KI_SELECT;
        case SDL_SCANCODE_PRINTSCREEN: return KI_SNAPSHOT;
        case SDL_SCANCODE_EXECUTE: return KI_EXECUTE;
        case SDL_SCANCODE_INSERT: return KI_INSERT;
        case SDL_SCANCODE_DELETE: return KI_DELETE;
        case SDL_SCANCODE_HELP: return KI_HELP;
        // --- Function ---
        case SDL_SCANCODE_F1: return KI_F1;
        case SDL_SCANCODE_F2: return KI_F2;
        case SDL_SCANCODE_F3: return KI_F3;
        case SDL_SCANCODE_F4: return KI_F4;
        case SDL_SCANCODE_F5: return KI_F5;
        case SDL_SCANCODE_F6: return KI_F6;
        case SDL_SCANCODE_F7: return KI_F7;
        case SDL_SCANCODE_F8: return KI_F8;
        case SDL_SCANCODE_F9: return KI_F9;
        case SDL_SCANCODE_F10: return KI_F10;
        case SDL_SCANCODE_F11: return KI_F11;
        case SDL_SCANCODE_F12: return KI_F12;
        case SDL_SCANCODE_F13: return KI_F13;
        case SDL_SCANCODE_F14: return KI_F14;
        case SDL_SCANCODE_F15: return KI_F15;
        case SDL_SCANCODE_F16: return KI_F16;
        case SDL_SCANCODE_F17: return KI_F17;
        case SDL_SCANCODE_F18: return KI_F18;
        case SDL_SCANCODE_F19: return KI_F19;
        case SDL_SCANCODE_F20: return KI_F20;
        case SDL_SCANCODE_F21: return KI_F21;
        case SDL_SCANCODE_F22: return KI_F22;
        case SDL_SCANCODE_F23: return KI_F23;
        case SDL_SCANCODE_F24: return KI_F24;
        // --- Keypad ---
        case SDL_SCANCODE_KP_0: return KI_NUMPAD0;
        case SDL_SCANCODE_KP_1: return KI_NUMPAD1;
        case SDL_SCANCODE_KP_2: return KI_NUMPAD2;
        case SDL_SCANCODE_KP_3: return KI_NUMPAD3;
        case SDL_SCANCODE_KP_4: return KI_NUMPAD4;
        case SDL_SCANCODE_KP_5: return KI_NUMPAD5;
        case SDL_SCANCODE_KP_6: return KI_NUMPAD6;
        case SDL_SCANCODE_KP_7: return KI_NUMPAD7;
        case SDL_SCANCODE_KP_8: return KI_NUMPAD8;
        case SDL_SCANCODE_KP_9: return KI_NUMPAD9;
        case SDL_SCANCODE_KP_ENTER: return KI_NUMPADENTER;
        case SDL_SCANCODE_KP_MULTIPLY: return KI_MULTIPLY;
        case SDL_SCANCODE_KP_PLUS: return KI_ADD;
        case SDL_SCANCODE_KP_MINUS: return KI_SUBTRACT;
        case SDL_SCANCODE_KP_PERIOD: return KI_DECIMAL;
        case SDL_SCANCODE_KP_DIVIDE: return KI_DIVIDE;
        case SDL_SCANCODE_KP_EQUALS: return KI_OEM_NEC_EQUAL;
        case SDL_SCANCODE_KP_EQUALSAS400: return KI_OEM_NEC_EQUAL;
        // --- OEM ---
        case SDL_SCANCODE_SEMICOLON: return KI_OEM_1;
        case SDL_SCANCODE_EQUALS: return KI_OEM_PLUS;
        case SDL_SCANCODE_COMMA: return KI_OEM_COMMA;
        case SDL_SCANCODE_MINUS: return KI_OEM_MINUS;
        case SDL_SCANCODE_PERIOD: return KI_OEM_PERIOD;
        case SDL_SCANCODE_SLASH: return KI_OEM_2;
        case SDL_SCANCODE_GRAVE: return KI_OEM_3;
        case SDL_SCANCODE_LEFTBRACKET: return KI_OEM_4;
        case SDL_SCANCODE_BACKSLASH: return KI_OEM_5;
        case SDL_SCANCODE_RIGHTBRACKET: return KI_OEM_6;
        case SDL_SCANCODE_APOSTROPHE: return KI_OEM_7;
        case SDL_SCANCODE_NONUSBACKSLASH: return KI_OEM_102;
        // --- Modifiers ---
        case SDL_SCANCODE_LSHIFT: return KI_LSHIFT;
        case SDL_SCANCODE_RSHIFT: return KI_RSHIFT;
        case SDL_SCANCODE_LCTRL: return KI_LCONTROL;
        case SDL_SCANCODE_RCTRL: return KI_RCONTROL;
        case SDL_SCANCODE_LALT: return KI_LMENU;
        case SDL_SCANCODE_RALT: return KI_RMENU;
        case SDL_SCANCODE_LGUI: return KI_LWIN;
        case SDL_SCANCODE_RGUI: return KI_RWIN;
        // --- Locks ---
        case SDL_SCANCODE_NUMLOCKCLEAR: return KI_NUMLOCK;
        case SDL_SCANCODE_SCROLLLOCK: return KI_SCROLL;
        case SDL_SCANCODE_PAUSE: return KI_PAUSE;
        // --- Browser ---
        case SDL_SCANCODE_AC_BACK: return KI_BROWSER_BACK;
        case SDL_SCANCODE_AC_FORWARD: return KI_BROWSER_FORWARD;
        case SDL_SCANCODE_AC_REFRESH: return KI_BROWSER_REFRESH;
        case SDL_SCANCODE_AC_STOP: return KI_BROWSER_STOP;
        case SDL_SCANCODE_AC_SEARCH: return KI_BROWSER_SEARCH;
        case SDL_SCANCODE_AC_BOOKMARKS: return KI_BROWSER_FAVORITES;
        case SDL_SCANCODE_AC_HOME: return KI_BROWSER_HOME;
        // --- Media ---
        case SDL_SCANCODE_VOLUMEUP: return KI_VOLUME_UP;
        case SDL_SCANCODE_VOLUMEDOWN: return KI_VOLUME_DOWN;
        case SDL_SCANCODE_MUTE: return KI_VOLUME_MUTE;
        // --- System ---
        case SDL_SCANCODE_APPLICATION: return KI_APPS;
        case SDL_SCANCODE_POWER: return KI_POWER;
        case SDL_SCANCODE_SLEEP: return KI_SLEEP;
        case SDL_SCANCODE_WAKE: return KI_WAKE;
        default: return KI_UNKNOWN;
    }
}

SDL_Scancode RmlSDL::KeyIdentifierToScancode(Rml::Input::KeyIdentifier ki) {
    using namespace Rml::Input;
    switch (ki) {
        case KI_A: return SDL_SCANCODE_A;
        case KI_B: return SDL_SCANCODE_B;
        case KI_C: return SDL_SCANCODE_C;
        case KI_D: return SDL_SCANCODE_D;
        case KI_E: return SDL_SCANCODE_E;
        case KI_F: return SDL_SCANCODE_F;
        case KI_G: return SDL_SCANCODE_G;
        case KI_H: return SDL_SCANCODE_H;
        case KI_I: return SDL_SCANCODE_I;
        case KI_J: return SDL_SCANCODE_J;
        case KI_K: return SDL_SCANCODE_K;
        case KI_L: return SDL_SCANCODE_L;
        case KI_M: return SDL_SCANCODE_M;
        case KI_N: return SDL_SCANCODE_N;
        case KI_O: return SDL_SCANCODE_O;
        case KI_P: return SDL_SCANCODE_P;
        case KI_Q: return SDL_SCANCODE_Q;
        case KI_R: return SDL_SCANCODE_R;
        case KI_S: return SDL_SCANCODE_S;
        case KI_T: return SDL_SCANCODE_T;
        case KI_U: return SDL_SCANCODE_U;
        case KI_V: return SDL_SCANCODE_V;
        case KI_W: return SDL_SCANCODE_W;
        case KI_X: return SDL_SCANCODE_X;
        case KI_Y: return SDL_SCANCODE_Y;
        case KI_Z: return SDL_SCANCODE_Z;
        case KI_0: return SDL_SCANCODE_0;
        case KI_1: return SDL_SCANCODE_1;
        case KI_2: return SDL_SCANCODE_2;
        case KI_3: return SDL_SCANCODE_3;
        case KI_4: return SDL_SCANCODE_4;
        case KI_5: return SDL_SCANCODE_5;
        case KI_6: return SDL_SCANCODE_6;
        case KI_7: return SDL_SCANCODE_7;
        case KI_8: return SDL_SCANCODE_8;
        case KI_9: return SDL_SCANCODE_9;
        case KI_SPACE: return SDL_SCANCODE_SPACE;
        case KI_RETURN: return SDL_SCANCODE_RETURN;
        case KI_ESCAPE: return SDL_SCANCODE_ESCAPE;
        case KI_BACK: return SDL_SCANCODE_BACKSPACE;
        case KI_TAB: return SDL_SCANCODE_TAB;
        case KI_CLEAR: return SDL_SCANCODE_CLEAR;
        case KI_CAPITAL: return SDL_SCANCODE_CAPSLOCK;
        case KI_PRIOR: return SDL_SCANCODE_PAGEUP;
        case KI_NEXT: return SDL_SCANCODE_PAGEDOWN;
        case KI_END: return SDL_SCANCODE_END;
        case KI_HOME: return SDL_SCANCODE_HOME;
        case KI_LEFT: return SDL_SCANCODE_LEFT;
        case KI_UP: return SDL_SCANCODE_UP;
        case KI_RIGHT: return SDL_SCANCODE_RIGHT;
        case KI_DOWN: return SDL_SCANCODE_DOWN;
        case KI_SELECT: return SDL_SCANCODE_SELECT;
        case KI_SNAPSHOT: return SDL_SCANCODE_PRINTSCREEN;
        case KI_EXECUTE: return SDL_SCANCODE_EXECUTE;
        case KI_INSERT: return SDL_SCANCODE_INSERT;
        case KI_DELETE: return SDL_SCANCODE_DELETE;
        case KI_HELP: return SDL_SCANCODE_HELP;
        case KI_F1: return SDL_SCANCODE_F1;
        case KI_F2: return SDL_SCANCODE_F2;
        case KI_F3: return SDL_SCANCODE_F3;
        case KI_F4: return SDL_SCANCODE_F4;
        case KI_F5: return SDL_SCANCODE_F5;
        case KI_F6: return SDL_SCANCODE_F6;
        case KI_F7: return SDL_SCANCODE_F7;
        case KI_F8: return SDL_SCANCODE_F8;
        case KI_F9: return SDL_SCANCODE_F9;
        case KI_F10: return SDL_SCANCODE_F10;
        case KI_F11: return SDL_SCANCODE_F11;
        case KI_F12: return SDL_SCANCODE_F12;
        case KI_F13: return SDL_SCANCODE_F13;
        case KI_F14: return SDL_SCANCODE_F14;
        case KI_F15: return SDL_SCANCODE_F15;
        case KI_F16: return SDL_SCANCODE_F16;
        case KI_F17: return SDL_SCANCODE_F17;
        case KI_F18: return SDL_SCANCODE_F18;
        case KI_F19: return SDL_SCANCODE_F19;
        case KI_F20: return SDL_SCANCODE_F20;
        case KI_F21: return SDL_SCANCODE_F21;
        case KI_F22: return SDL_SCANCODE_F22;
        case KI_F23: return SDL_SCANCODE_F23;
        case KI_F24: return SDL_SCANCODE_F24;
        case KI_NUMPAD0: return SDL_SCANCODE_KP_0;
        case KI_NUMPAD1: return SDL_SCANCODE_KP_1;
        case KI_NUMPAD2: return SDL_SCANCODE_KP_2;
        case KI_NUMPAD3: return SDL_SCANCODE_KP_3;
        case KI_NUMPAD4: return SDL_SCANCODE_KP_4;
        case KI_NUMPAD5: return SDL_SCANCODE_KP_5;
        case KI_NUMPAD6: return SDL_SCANCODE_KP_6;
        case KI_NUMPAD7: return SDL_SCANCODE_KP_7;
        case KI_NUMPAD8: return SDL_SCANCODE_KP_8;
        case KI_NUMPAD9: return SDL_SCANCODE_KP_9;
        case KI_NUMPADENTER: return SDL_SCANCODE_KP_ENTER;
        case KI_MULTIPLY: return SDL_SCANCODE_KP_MULTIPLY;
        case KI_ADD: return SDL_SCANCODE_KP_PLUS;
        case KI_SUBTRACT: return SDL_SCANCODE_KP_MINUS;
        case KI_DECIMAL: return SDL_SCANCODE_KP_PERIOD;
        case KI_DIVIDE: return SDL_SCANCODE_KP_DIVIDE;
        case KI_OEM_NEC_EQUAL: return SDL_SCANCODE_KP_EQUALS; // Note: also mapped from SDL_SCANCODE_KP_EQUALSAS400
        case KI_OEM_1: return SDL_SCANCODE_SEMICOLON;
        case KI_OEM_PLUS: return SDL_SCANCODE_EQUALS;
        case KI_OEM_COMMA: return SDL_SCANCODE_COMMA;
        case KI_OEM_MINUS: return SDL_SCANCODE_MINUS;
        case KI_OEM_PERIOD: return SDL_SCANCODE_PERIOD;
        case KI_OEM_2: return SDL_SCANCODE_SLASH;
        case KI_OEM_3: return SDL_SCANCODE_GRAVE;
        case KI_OEM_4: return SDL_SCANCODE_LEFTBRACKET;
        case KI_OEM_5: return SDL_SCANCODE_BACKSLASH;
        case KI_OEM_6: return SDL_SCANCODE_RIGHTBRACKET;
        case KI_OEM_7: return SDL_SCANCODE_APOSTROPHE;
        case KI_OEM_102: return SDL_SCANCODE_NONUSBACKSLASH;
        case KI_LSHIFT: return SDL_SCANCODE_LSHIFT;
        case KI_RSHIFT: return SDL_SCANCODE_RSHIFT;
        case KI_LCONTROL: return SDL_SCANCODE_LCTRL;
        case KI_RCONTROL: return SDL_SCANCODE_RCTRL;
        case KI_LMENU: return SDL_SCANCODE_LALT;
        case KI_RMENU: return SDL_SCANCODE_RALT;
        case KI_LWIN: return SDL_SCANCODE_LGUI;
        case KI_RWIN: return SDL_SCANCODE_RGUI;
        case KI_NUMLOCK: return SDL_SCANCODE_NUMLOCKCLEAR;
        case KI_SCROLL: return SDL_SCANCODE_SCROLLLOCK;
        case KI_PAUSE: return SDL_SCANCODE_PAUSE;
        case KI_BROWSER_BACK: return SDL_SCANCODE_AC_BACK;
        case KI_BROWSER_FORWARD: return SDL_SCANCODE_AC_FORWARD;
        case KI_BROWSER_REFRESH: return SDL_SCANCODE_AC_REFRESH;
        case KI_BROWSER_STOP: return SDL_SCANCODE_AC_STOP;
        case KI_BROWSER_SEARCH: return SDL_SCANCODE_AC_SEARCH;
        case KI_BROWSER_FAVORITES: return SDL_SCANCODE_AC_BOOKMARKS;
        case KI_BROWSER_HOME: return SDL_SCANCODE_AC_HOME;
        case KI_VOLUME_UP: return SDL_SCANCODE_VOLUMEUP;
        case KI_VOLUME_DOWN: return SDL_SCANCODE_VOLUMEDOWN;
        case KI_VOLUME_MUTE: return SDL_SCANCODE_MUTE;
        case KI_APPS: return SDL_SCANCODE_APPLICATION;
        case KI_POWER: return SDL_SCANCODE_POWER;
        case KI_SLEEP: return SDL_SCANCODE_SLEEP;
        case KI_WAKE: return SDL_SCANCODE_WAKE;
        default: return SDL_SCANCODE_UNKNOWN;
    }
}

Rml::Input::KeyIdentifier RmlSDL::SDLKeyToKeyIdentifier(int sdlkey) {
#if SDL_MAJOR_VERSION >= 3
	constexpr auto key_a = SDLK_A;
	constexpr auto key_b = SDLK_B;
	constexpr auto key_c = SDLK_C;
	constexpr auto key_d = SDLK_D;
	constexpr auto key_e = SDLK_E;
	constexpr auto key_f = SDLK_F;
	constexpr auto key_g = SDLK_G;
	constexpr auto key_h = SDLK_H;
	constexpr auto key_i = SDLK_I;
	constexpr auto key_j = SDLK_J;
	constexpr auto key_k = SDLK_K;
	constexpr auto key_l = SDLK_L;
	constexpr auto key_m = SDLK_M;
	constexpr auto key_n = SDLK_N;
	constexpr auto key_o = SDLK_O;
	constexpr auto key_p = SDLK_P;
	constexpr auto key_q = SDLK_Q;
	constexpr auto key_r = SDLK_R;
	constexpr auto key_s = SDLK_S;
	constexpr auto key_t = SDLK_T;
	constexpr auto key_u = SDLK_U;
	constexpr auto key_v = SDLK_V;
	constexpr auto key_w = SDLK_W;
	constexpr auto key_x = SDLK_X;
	constexpr auto key_y = SDLK_Y;
	constexpr auto key_z = SDLK_Z;
	constexpr auto key_grave = SDLK_GRAVE;
	constexpr auto key_dblapostrophe = SDLK_DBLAPOSTROPHE;
#else
	constexpr auto key_a = SDLK_a;
	constexpr auto key_b = SDLK_b;
	constexpr auto key_c = SDLK_c;
	constexpr auto key_d = SDLK_d;
	constexpr auto key_e = SDLK_e;
	constexpr auto key_f = SDLK_f;
	constexpr auto key_g = SDLK_g;
	constexpr auto key_h = SDLK_h;
	constexpr auto key_i = SDLK_i;
	constexpr auto key_j = SDLK_j;
	constexpr auto key_k = SDLK_k;
	constexpr auto key_l = SDLK_l;
	constexpr auto key_m = SDLK_m;
	constexpr auto key_n = SDLK_n;
	constexpr auto key_o = SDLK_o;
	constexpr auto key_p = SDLK_p;
	constexpr auto key_q = SDLK_q;
	constexpr auto key_r = SDLK_r;
	constexpr auto key_s = SDLK_s;
	constexpr auto key_t = SDLK_t;
	constexpr auto key_u = SDLK_u;
	constexpr auto key_v = SDLK_v;
	constexpr auto key_w = SDLK_w;
	constexpr auto key_x = SDLK_x;
	constexpr auto key_y = SDLK_y;
	constexpr auto key_z = SDLK_z;
	constexpr auto key_grave = SDLK_BACKQUOTE;
	constexpr auto key_dblapostrophe = SDLK_QUOTEDBL;
#endif

	switch (sdlkey) {
	case SDLK_UNKNOWN:      return Rml::Input::KI_UNKNOWN;
	case SDLK_ESCAPE:       return Rml::Input::KI_ESCAPE;
	case SDLK_SPACE:        return Rml::Input::KI_SPACE;
	case SDLK_0:            return Rml::Input::KI_0;
	case SDLK_1:            return Rml::Input::KI_1;
	case SDLK_2:            return Rml::Input::KI_2;
	case SDLK_3:            return Rml::Input::KI_3;
	case SDLK_4:            return Rml::Input::KI_4;
	case SDLK_5:            return Rml::Input::KI_5;
	case SDLK_6:            return Rml::Input::KI_6;
	case SDLK_7:            return Rml::Input::KI_7;
	case SDLK_8:            return Rml::Input::KI_8;
	case SDLK_9:            return Rml::Input::KI_9;
	case key_a:             return Rml::Input::KI_A;
	case key_b:             return Rml::Input::KI_B;
	case key_c:             return Rml::Input::KI_C;
	case key_d:             return Rml::Input::KI_D;
	case key_e:             return Rml::Input::KI_E;
	case key_f:             return Rml::Input::KI_F;
	case key_g:             return Rml::Input::KI_G;
	case key_h:             return Rml::Input::KI_H;
	case key_i:             return Rml::Input::KI_I;
	case key_j:             return Rml::Input::KI_J;
	case key_k:             return Rml::Input::KI_K;
	case key_l:             return Rml::Input::KI_L;
	case key_m:             return Rml::Input::KI_M;
	case key_n:             return Rml::Input::KI_N;
	case key_o:             return Rml::Input::KI_O;
	case key_p:             return Rml::Input::KI_P;
	case key_q:             return Rml::Input::KI_Q;
	case key_r:             return Rml::Input::KI_R;
	case key_s:             return Rml::Input::KI_S;
	case key_t:             return Rml::Input::KI_T;
	case key_u:             return Rml::Input::KI_U;
	case key_v:             return Rml::Input::KI_V;
	case key_w:             return Rml::Input::KI_W;
	case key_x:             return Rml::Input::KI_X;
	case key_y:             return Rml::Input::KI_Y;
	case key_z:             return Rml::Input::KI_Z;
	case SDLK_SEMICOLON:    return Rml::Input::KI_OEM_1;
	case SDLK_EQUALS:       return Rml::Input::KI_OEM_PLUS;
	case SDLK_COMMA:        return Rml::Input::KI_OEM_COMMA;
	case SDLK_MINUS:        return Rml::Input::KI_OEM_MINUS;
	case SDLK_PERIOD:       return Rml::Input::KI_OEM_PERIOD;
	case SDLK_SLASH:        return Rml::Input::KI_OEM_2;
	case key_grave:         return Rml::Input::KI_OEM_3;
	case SDLK_LEFTBRACKET:  return Rml::Input::KI_OEM_4;
	case SDLK_BACKSLASH:    return Rml::Input::KI_OEM_5;
	case SDLK_RIGHTBRACKET: return Rml::Input::KI_OEM_6;
	case key_dblapostrophe: return Rml::Input::KI_OEM_7;
	case SDLK_KP_0:         return Rml::Input::KI_NUMPAD0;
	case SDLK_KP_1:         return Rml::Input::KI_NUMPAD1;
	case SDLK_KP_2:         return Rml::Input::KI_NUMPAD2;
	case SDLK_KP_3:         return Rml::Input::KI_NUMPAD3;
	case SDLK_KP_4:         return Rml::Input::KI_NUMPAD4;
	case SDLK_KP_5:         return Rml::Input::KI_NUMPAD5;
	case SDLK_KP_6:         return Rml::Input::KI_NUMPAD6;
	case SDLK_KP_7:         return Rml::Input::KI_NUMPAD7;
	case SDLK_KP_8:         return Rml::Input::KI_NUMPAD8;
	case SDLK_KP_9:         return Rml::Input::KI_NUMPAD9;
	case SDLK_KP_ENTER:     return Rml::Input::KI_NUMPADENTER;
	case SDLK_KP_MULTIPLY:  return Rml::Input::KI_MULTIPLY;
	case SDLK_KP_PLUS:      return Rml::Input::KI_ADD;
	case SDLK_KP_MINUS:     return Rml::Input::KI_SUBTRACT;
	case SDLK_KP_PERIOD:    return Rml::Input::KI_DECIMAL;
	case SDLK_KP_DIVIDE:    return Rml::Input::KI_DIVIDE;
	case SDLK_KP_EQUALS:    return Rml::Input::KI_OEM_NEC_EQUAL;
	case SDLK_BACKSPACE:    return Rml::Input::KI_BACK;
	case SDLK_TAB:          return Rml::Input::KI_TAB;
	case SDLK_CLEAR:        return Rml::Input::KI_CLEAR;
	case SDLK_RETURN:       return Rml::Input::KI_RETURN;
	case SDLK_PAUSE:        return Rml::Input::KI_PAUSE;
	case SDLK_CAPSLOCK:     return Rml::Input::KI_CAPITAL;
	case SDLK_PAGEUP:       return Rml::Input::KI_PRIOR;
	case SDLK_PAGEDOWN:     return Rml::Input::KI_NEXT;
	case SDLK_END:          return Rml::Input::KI_END;
	case SDLK_HOME:         return Rml::Input::KI_HOME;
	case SDLK_LEFT:         return Rml::Input::KI_LEFT;
	case SDLK_UP:           return Rml::Input::KI_UP;
	case SDLK_RIGHT:        return Rml::Input::KI_RIGHT;
	case SDLK_DOWN:         return Rml::Input::KI_DOWN;
	case SDLK_INSERT:       return Rml::Input::KI_INSERT;
	case SDLK_DELETE:       return Rml::Input::KI_DELETE;
	case SDLK_HELP:         return Rml::Input::KI_HELP;
	case SDLK_F1:           return Rml::Input::KI_F1;
	case SDLK_F2:           return Rml::Input::KI_F2;
	case SDLK_F3:           return Rml::Input::KI_F3;
	case SDLK_F4:           return Rml::Input::KI_F4;
	case SDLK_F5:           return Rml::Input::KI_F5;
	case SDLK_F6:           return Rml::Input::KI_F6;
	case SDLK_F7:           return Rml::Input::KI_F7;
	case SDLK_F8:           return Rml::Input::KI_F8;
	case SDLK_F9:           return Rml::Input::KI_F9;
	case SDLK_F10:          return Rml::Input::KI_F10;
	case SDLK_F11:          return Rml::Input::KI_F11;
	case SDLK_F12:          return Rml::Input::KI_F12;
	case SDLK_F13:          return Rml::Input::KI_F13;
	case SDLK_F14:          return Rml::Input::KI_F14;
	case SDLK_F15:          return Rml::Input::KI_F15;
	case SDLK_NUMLOCKCLEAR: return Rml::Input::KI_NUMLOCK;
	case SDLK_SCROLLLOCK:   return Rml::Input::KI_SCROLL;
	case SDLK_LSHIFT:       return Rml::Input::KI_LSHIFT;
	case SDLK_RSHIFT:       return Rml::Input::KI_RSHIFT;
	case SDLK_LCTRL:        return Rml::Input::KI_LCONTROL;
	case SDLK_RCTRL:        return Rml::Input::KI_RCONTROL;
	case SDLK_LALT:         return Rml::Input::KI_LMENU;
	case SDLK_RALT:         return Rml::Input::KI_RMENU;
	case SDLK_LGUI:         return Rml::Input::KI_LMETA;
	case SDLK_RGUI:         return Rml::Input::KI_RMETA;
	default: break;
	}

	return Rml::Input::KI_UNKNOWN;
}

Rml::Input::KeyIdentifier RmlSDL::ScancodeToKeyIdentifierBasedOnLayout(SDL_Scancode scancode) {
    SDL_Keycode keycode = SDL_GetKeyFromScancode(scancode, SDL_KMOD_NONE, false);
    return SDLKeyToKeyIdentifier(keycode);
}

Rml::Input::KeyIdentifier RmlSDL::TransformKeyIdentifierForLayout(Rml::Input::KeyIdentifier ki) {
    SDL_Scancode scancode = KeyIdentifierToScancode(ki);
    return ScancodeToKeyIdentifierBasedOnLayout(scancode);
}
